version: '3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception_network
        restart: always

    wordpress:
        container_name: wordpress
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        volumes:
            - wordpress:/var/www/html
        env_file:
            - .env
        networks:
            - inception_network
        restart: always

    nginx:
        container_name: nginx
        depends_on:
            - wordpress
        build: ./requirements/nginx
        volumes:
            - wordpress:/var/www/html
        ports:
            - "443:443"
        networks:
            - inception_network
        restart: always

volumes:
    mariadb:
        driver_opts:
            device: /Users/thomas/Desktop/d
            o: bind
            type: none

    wordpress:
        driver_opts:
            device: /Users/thomas/Desktop/w
            o: bind
            type: none

networks:
    inception_network:
        driver: bridge
