version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
     - "443:443"
    restart: always
    networks:
     - network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
     - network

networks:
  network:
    driver: bridge
